apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ben
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/g7l4n5q7/ben:latest
        ports:
        - containerPort: 80
